name: CD
on:
  - push

jobs:
  build-linux-win:
    name: win build (mxe)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Add mxe.cc repo
      run: |
        sudo apt-key adv \
        --keyserver keyserver.ubuntu.com \
        --recv-keys 86B72ED9 
        sudo add-apt-repository \
          "deb [arch=amd64] https://pkg.mxe.cc/repos/apt `lsb_release -sc` main" 
      
    - name: Updates
      run: sudo apt-get update

    - name: Dependencies
      run: |
        sudo apt-get install mxe-x86-64-w64-mingw32.shared-cairo \
             mxe-x86-64-w64-mingw32.shared-curl \
             mxe-x86-64-w64-mingw32.shared-freetype \
             mxe-x86-64-w64-mingw32.shared-glib \
             mxe-x86-64-w64-mingw32.shared-jpeg \
             mxe-x86-64-w64-mingw32.shared-lcms \
             mxe-x86-64-w64-mingw32.shared-libpng \
             mxe-x86-64-w64-mingw32.shared-libwebp \
             mxe-x86-64-w64-mingw32.shared-openjpeg \
             mxe-x86-64-w64-mingw32.shared-poppler \
             mxe-x86-64-w64-mingw32.shared-qtbase \
             mxe-x86-64-w64-mingw32.shared-qtdeclarative \
             mxe-x86-64-w64-mingw32.shared-qtscript \
             mxe-x86-64-w64-mingw32.shared-qttools \
             mxe-x86-64-w64-mingw32.shared-tiff \
             mxe-x86-64-w64-mingw32.shared-zlib \
             mxe-x86-64-w64-mingw32.static-nsis

    - name: Configure
      run: |
        MXEDIR="/usr/lib/mxe"
        MXETARGET="x86_64-w64-mingw32.shared"
        PATH=$PATH:${MXEDIR}/usr/bin
        $MXEDIR/usr/bin/${MXETARGET}-qmake-qt5 texstudio.pro CONFIG-=debug MXE=1 BUILD_ADWAITA=1

    - name: Build
      run: |
        MXEDIR="/usr/lib/mxe"
        MXETARGET="x86_64-w64-mingw32.shared"
        PATH=$PATH:${MXEDIR}/usr/bin
        make -j 2
      
    - name: Package
      id: package
      run: |
        MXEDIR="/usr/lib/mxe"
        MXETARGET="x86_64-w64-mingw32.shared"
        PATH=$PATH:${MXEDIR}/usr/bin
        . ./.github/scripts/get-version.sh
        .github/scripts/package_win.sh
        echo "::set-output name=VERSION_NAME::${VERSION_NAME}"
        
    - name: Deploy zip to Bintray
      if: github.event_name == 'push'
      uses: ./.github/actions/deploy-bintray
      with:
        file: ./package-zip/texstudio-win-${{ steps.package.outputs.VERSION_NAME }}.zip
        subject: sunderme
        repo: texstudio
        pkg: texstudio-win
        version: ${{ steps.package.outputs.VERSION_NAME }}
        username: sunderme
        key: ${{ secrets.bintrayAPI }}
        
    - name: Deploy exe to Bintray
      if: github.event_name == 'push'
      uses: ./.github/actions/deploy-bintray
      with:
        file: texstudio-win-${{ steps.package.outputs.VERSION_NAME }}.exe
        subject: sunderme
        repo: texstudio
        pkg: texstudio-win
        version: ${{ steps.package.outputs.VERSION_NAME }}
        username: sunderme
        key: ${{ secrets.bintrayAPI }}
      
###################################

  build-linux-release:
    name: linux appimage
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Updates
      run: sudo apt-get update

    - name: Dependencies
      run: sudo apt-get install qtbase5-dev qt5-default qt5-qmake libqt5svg5-dev qtscript5-dev qttools5-dev libqt5svg5-dev libpoppler-qt5-dev pkg-config zlib1g-dev 

    - name: Configure
      run: qmake texstudio.pro CONFIG-=debug

    - name: Build
      run: make -j 2
      
    - name: Package
      id: package
      run: |
        POPPLERDATA_VERSION="0.4.8"
        POPPLERDATA_SUBDIR="poppler-data-${POPPLERDATA_VERSION}"
        POPPLERDATA_FILE="poppler-data-${POPPLERDATA_VERSION}.tar.gz"
        POPPLERDATA_URL="https://poppler.freedesktop.org/${POPPLERDATA_FILE}"
        POPPLERDATA_SHA256="1096a18161f263cccdc6d8a2eb5548c41ff8fcf9a3609243f1b6296abdf72872"
        . ./.github/scripts/get-version.sh
        . ./.github/scripts/package_linux.sh
        echo "::set-output name=VERSION_NAME::${VERSION_NAME}"
        echo "::set-output name=VERSION::${VERSION}"
        
    - name: Upload to Bintray
      uses: bpicode/github-action-upload-bintray@master
      with:
        file: texstudio-linux-${{ steps.package.outputs.VERSION_NAME }}-x86_64.AppImage
        api_user: sunderme
        api_key: ${{ secrets.bintrayAPI }}
        repository_user: sunderme
        repository: texstudio
        package: texstudio-linux
        version: ${{ steps.package.outputs.VERSION_NAME }}
        publish: 1
        calculate_metadata: false
     
############################
      
  macosx-bintray:
    name: Mac OS X (Bintray)
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        # /usr/local/bin/2to3 is symlinked to the native python2 installation
        # but prevents the homebrew install from succeeding
        rm -f /usr/local/bin/2to3
        brew update > brew_update.log || { echo "::error::Updating homebrew failed"; cat brew_update.log; exit 1; }
        brew install poppler qt5

    - name: Configure
      run: /usr/local/opt/qt/bin/qmake texstudio.pro CONFIG-=debug

    - name: Build
      run: make -j 2

    - name: Package
      id: package
      run: |
        /usr/local/opt/qt5/bin/macdeployqt texstudio.app -dmg
        . ./.github/scripts/get-version.sh
        mv texstudio.dmg texstudio-osx-${VERSION_NAME}.dmg
        echo "::set-output name=VERSION_NAME::${VERSION_NAME}"
        
    - name: Deploy to Bintray
      if: github.event_name == 'push'
      uses: ./.github/actions/deploy-bintray
      with:
        file: texstudio-osx-${{ steps.package.outputs.VERSION_NAME }}.dmg
        subject: sunderme
        repo: texstudio
        pkg: texstudio-osx
        version: ${{ steps.package.outputs.VERSION_NAME}}
        username: sunderme
        key: ${{ secrets.bintrayAPI }}
   


